Hunter Herman is space Jesus
Hunter helped me bugfix. Mostly helped point out why my code didn't belong where it did, and that static_type is not the same as static_type()

AttributeError: 'function' object has no attribute 'is_subtype_of' has plagued me no longer.